/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laboratorio.pkg5;

import java.util.List;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Proyector
 */
public class FrameEstudiantes extends javax.swing.JFrame {
    DefaultListModel modelo = new DefaultListModel();
    List<Estudiante> estudiantes = new ArrayList<Estudiante>();
    //COLECCION              //TIPO ESTUDIANTE
    
    /**
     * Creates new form FrameEstudiante
     */
    public FrameEstudiantes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txt_buscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbl_agregar = new javax.swing.JLabel();
        lbl_editar = new javax.swing.JLabel();
        lbl_eliminar = new javax.swing.JLabel();
        lbl_buscar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_buscar.setBackground(new java.awt.Color(0, 0, 0));
        txt_buscar.setForeground(new java.awt.Color(255, 255, 255));
        txt_buscar.setBorder(null);
        txt_buscar.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txt_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 180, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio/pkg5/Rectangle 1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 220, 40));

        lbl_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio/pkg5/Group 2.png"))); // NOI18N
        lbl_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_agregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_agregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_agregarMouseExited(evt);
            }
        });

        lbl_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio/pkg5/Group 3.png"))); // NOI18N
        lbl_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_editarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_editarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_editarMouseExited(evt);
            }
        });

        lbl_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio/pkg5/Group 4.png"))); // NOI18N
        lbl_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_eliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_eliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_eliminarMouseExited(evt);
            }
        });

        lbl_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio/pkg5/Group 1.png"))); // NOI18N
        lbl_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_buscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_buscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_buscarMouseExited(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio/pkg5/Group 7.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jList1.setBackground(new java.awt.Color(0, 0, 0));
        jList1.setBorder(null);
        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jList1.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(jList1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 160));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio/pkg5/Group 8.png"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 330, 240));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio/pkg5/Estudiantes.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(lbl_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lbl_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 175, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)))
                        .addGap(34, 34, 34)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(222, 222, 222)))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_buscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_buscarMouseEntered
        // TODO add your handling code here:
          lbl_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio/pkg5/Group 11.png"))); 
    }//GEN-LAST:event_lbl_buscarMouseEntered

    private void lbl_buscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_buscarMouseExited
        // TODO add your handling code here:
         lbl_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio/pkg5/Group 1.png"))); 
    }//GEN-LAST:event_lbl_buscarMouseExited

    private void lbl_agregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_agregarMouseEntered
        // TODO add your handling code here:
         lbl_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio/pkg5/Group 22.png"))); 
    }//GEN-LAST:event_lbl_agregarMouseEntered

    private void lbl_agregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_agregarMouseExited
        // TODO add your handling code here:
         lbl_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio/pkg5/Group 2.png"))); 
    }//GEN-LAST:event_lbl_agregarMouseExited

    private void lbl_editarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_editarMouseEntered
        // TODO add your handling code here:
        lbl_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio/pkg5/Group 33.png"))); 
    }//GEN-LAST:event_lbl_editarMouseEntered

    private void lbl_editarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_editarMouseExited
        // TODO add your handling code here:
        lbl_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio/pkg5/Group 3.png"))); 
    }//GEN-LAST:event_lbl_editarMouseExited

    private void lbl_eliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_eliminarMouseEntered
        // TODO add your handling code here:
        lbl_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio/pkg5/Group 44.png"))); 
    }//GEN-LAST:event_lbl_eliminarMouseEntered

    private void lbl_eliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_eliminarMouseExited
        // TODO add your handling code here:
         lbl_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio/pkg5/Group 4.png"))); 
    }//GEN-LAST:event_lbl_eliminarMouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void lbl_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_agregarMouseClicked
        // TODO add your handling code here:
       llamarPantallaEdicion();
        
        
        
    }//GEN-LAST:event_lbl_agregarMouseClicked

    private void lbl_editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_editarMouseClicked
        // TODO add your handling code here:

         int index = jList1.getSelectedIndex();
         if (index != -1) {
        Estudiante estudiante = estudiantes.get(index);
        llamarPantallaEdicion(estudiante);
         }   
       
    }//GEN-LAST:event_lbl_editarMouseClicked

    
    private void lbl_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_eliminarMouseClicked
        // TODO add your handling code here:

     int selectedIndex = jList1.getSelectedIndex();
    if (selectedIndex != -1) {
        // Obtén el estudiante seleccionado
        Estudiante estudiante = estudiantes.get(selectedIndex);

        // Elimina el estudiante tanto del modelo como de la lista de estudiantes
        modelo.remove(selectedIndex);
        estudiantes.remove(selectedIndex);

        // Actualiza el modelo del JList
        jList1.setModel(modelo);

    }    
   
    }//GEN-LAST:event_lbl_eliminarMouseClicked

    private void lbl_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_buscarMouseClicked
        // TODO add your handling code here:
        
   String criterioBusqueda = txt_buscar.getText().toLowerCase(); // Obtén el criterio de búsqueda en minúsculas
    
    DefaultListModel nuevoModelo = new DefaultListModel(); // Crea un nuevo modelo de lista
    
    for (Estudiante estudiante : estudiantes) {
        // Convierte el nombre y apellido del estudiante a minúsculas para que la búsqueda no sea sensible a mayúsculas/minúsculas
        String nombreCompleto = estudiante.getNombre().toLowerCase() + " " + estudiante.getApellido().toLowerCase();
        
        // Compara el nombre completo del estudiante con el criterio de búsqueda
        if (nombreCompleto.contains(criterioBusqueda)) {
            // Si coincide, agrega el estudiante al nuevo modelo de lista
            nuevoModelo.addElement(estudiante.getTexto());
        }
    }
    
    // Actualiza el JList con el nuevo modelo de lista que contiene los resultados de la búsqueda
    jList1.setModel(nuevoModelo);
        
        
    }//GEN-LAST:event_lbl_buscarMouseClicked

     public void agregarEstudiante(Estudiante estudiante){//va a recibir un estudiante
         /*A mi lista de estudiante (le agrego el estudiante)
         una vez que lo agregue a mi modelo , falta agregarlo al list view*/
        estudiantes.add(estudiante);
        modelo.addElement(estudiante.getTexto());//Get texto me devuelve el apellido y nombre
        jList1.setModel(modelo);
     }
    
    
    private void llamarPantallaEdicion(){
    
    FrameEstudiante estudiante = new FrameEstudiante(this);
    estudiante.setLocationRelativeTo(null);
    estudiante.setVisible(true);
    this.setVisible(false);
    
    }
    
       private void llamarPantallaEdicion(Estudiante estudiante){
    
    FrameEstudiante PantallaEstudiante = new FrameEstudiante(this,estudiante );
    PantallaEstudiante.setLocationRelativeTo(null);
    PantallaEstudiante.setVisible(true);
    this.setVisible(false);
    
    }
    
    public void actualizarEstudiante(Estudiante estudiante) {
    // Encuentra el índice del estudiante en la lista y actualiza su información.
    int index = estudiantes.indexOf(estudiante);
    if (index != -1) {
        estudiantes.set(index, estudiante);
        modelo.set(index, estudiante.getTexto());
    }
}
       
 
       
       
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameEstudiantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_agregar;
    private javax.swing.JLabel lbl_buscar;
    private javax.swing.JLabel lbl_editar;
    private javax.swing.JLabel lbl_eliminar;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables
}
